# Generated by Django 4.2.6 on 2024-01-28 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plate",
            fields=[
                (
                    "numberPlate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="User_Service.vehicle",
                    ),
                ),
                ("region", models.CharField(max_length=100)),
                ("postal_area", models.CharField(max_length=100)),
                ("age_identifier", models.JSONField()),
                ("random_letters", models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name="driver",
            name="driverPhone",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="JunctionsLog",
            fields=[
                ("logID", models.AutoField(primary_key=True, serialize=False)),
                ("dateTime", models.DateTimeField()),
                ("location", models.CharField(max_length=100)),
                ("event", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                (
                    "numberPlate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="User_Service.plate",
                    ),
                ),
            ],
        ),
    ]
