# Generated by Django 4.2.6 on 2024-01-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="junctionslog",
            name="numberPlate",
            field=models.CharField(max_length=20),
        ),
    ]
