# Generated by Django 4.2.6 on 2024-02-04 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0002_alter_junctionslog_numberplate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Violation",
            fields=[
                ("logID", models.AutoField(primary_key=True, serialize=False)),
                ("violationType", models.CharField(max_length=255)),
                ("fineAmount", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ViolationLog",
            fields=[
                ("logID", models.AutoField(primary_key=True, serialize=False)),
                ("numberPlate", models.CharField(max_length=255)),
                ("dateTime", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                (
                    "violationType",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="User_Service.violation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FineLog",
            fields=[
                ("logID", models.AutoField(primary_key=True, serialize=False)),
                ("numberPlate", models.CharField(max_length=255)),
                ("driverName", models.CharField(max_length=255)),
                ("dateTime", models.CharField(max_length=255)),
                ("location", models.CharField(max_length=255)),
                ("fineAmount", models.IntegerField()),
                ("closedStatus", models.BooleanField()),
                (
                    "driverID",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="User_Service.driver",
                    ),
                ),
                (
                    "violationType",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="User_Service.violation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                ("logID", models.AutoField(primary_key=True, serialize=False)),
                ("driverEmail", models.EmailField(max_length=255)),
                ("dateTime", models.CharField(max_length=255)),
                ("sentStatus", models.BooleanField()),
                (
                    "fineLogID",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="User_Service.finelog",
                    ),
                ),
            ],
        ),
    ]
