# Generated by Django 4.2.6 on 2024-01-28 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0002_plate_alter_driver_driverphone_junctionslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plate",
            name="numberPlate",
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="numberPlate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="User_Service.plate",
            ),
        ),
    ]
