# Generated by Django 4.2.6 on 2024-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0003_violation_violationlog_finelog_emaillog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="junctionslog",
            name="event",
        ),
        migrations.RemoveField(
            model_name="junctionslog",
            name="status",
        ),
        migrations.AddField(
            model_name="junctionslog",
            name="beltStatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="junctionslog",
            name="hitSuspicion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="junctionslog",
            name="phoneStatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="junctionslog",
            name="redlightSuspicion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="junctionslog",
            name="registerStatus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="junctionslog",
            name="speed",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="driver",
            name="driverPhone",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="finelog",
            name="fineAmount",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="junctionslog",
            name="location",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="violation",
            name="fineAmount",
            field=models.IntegerField(default=0),
        ),
    ]
