# Generated by Django 4.2.6 on 2024-02-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0005_alter_vehicle_numberplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="numberPlate",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="User_Service.plate",
            ),
        ),
    ]
