# Generated by Django 4.2.6 on 2024-02-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0006_alter_vehicle_numberplate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finelog",
            name="dateTime",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="violationlog",
            name="dateTime",
            field=models.DateTimeField(),
        ),
    ]
