# Generated by Django 4.2.6 on 2024-02-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User_Service", "0007_alter_finelog_datetime_alter_violationlog_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finelog",
            name="driverID",
            field=models.BigIntegerField(),
        ),
    ]
